INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Ali', 'get AWS certified', CURRENT_DATE(), false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Ali', 'Learn FullStack', CURRENT_DATE(), false);
INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Ali', 'Meow Meow Meow', CURRENT_DATE(), false);